os: linux
dist: focal
group: edge
language: python
keys:
  - PEM
env:
  secret: “encrypted_d0fccec9559d_key” # encrypted COSIGN_PASSWORD=...  string; see cosign doc
before_script: 
  - travis_key PEM cosign.key  # cosign requires the key to be in a file
  

script:
  - cosign sign --key cosign.pem arthanaharidas/python-hello-world

