os: linux
dist: focal
group: edge
language: python
keys:
  - PEM
env:
  - PRIVATE_KEY_PASSWORD=Pankaj@1992$

before_script: 
  - travis_key PEM cosign.key  # cosign requires the key to be in a file
  

script:
  - cosign sign --key cosign.pem arthanaharidas/python-hello-world
before_install:
  - export COSIGN_PASSWORD=$PRIVATE_KEY_PASSWORD
  - openssl aes-256-cbc -K $encrypted_d0fccec9559d_key -iv $encrypted_d0fccec9559d_iv -in cosign.pem.enc -out cosign.pem -d
