os: linux
dist: focal
group: edge
language: python
keys:
  - PEM
env:
  secret: “encrypted_51f11bfbfc28_iv” # encrypted COSIGN_PASSWORD=...  string; see cosign doc
before_script: 
  - travis_key PEM cosign.key  # cosign requires the key to be in a file

script: 
  - cosign sign --key cosign.key arthanaharidas/python-hello-world
  
before_install:
  - openssl aes-256-cbc -K $encrypted_51f11bfbfc28_key -iv $encrypted_51f11bfbfc28_iv -in cosign.key.enc -out cosign.key -d
