os: linux
dist: focal
group: edge
language: python
keys:
  - PEM
env:
  secret: “key” # encrypted COSIGN_PASSWORD=...  string; see cosign doc
before_script: 
  - travis_key PEM cosign.key  # cosign requires the key to be in a file

script: 
  - cosign sign --key cosign.key arthanaharidas/python-hello-world
  
before_install:
   
   - openssl aes-256-cbc -k "Pankaj@1992$" -in cosign.key -out cosign.key.enc
   - openssl aes-256-cbc -k "$KEY_PASSWORD" -in cosign.key.enc -out cosign.key -d

